config/routes.rb
Rails.application.routes.draw do
  
 resources :cathegories do
  resources :plants
 end


   root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/cathegory.rb
class Cathegory < ActiveRecord::Base
    has_many :plants
    #validates :cat, presence: true,
    #length: { minimum: 3 }
end

app/models/plant.rb
class Plant < ActiveRecord::Base
  belongs_to :cathegory
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cathegories_controller.rb
class CathegoriesController < ApplicationController
    
    def index
    @cathegories = Cathegory.all
    end
  
  def show
    @cathegory = Cathegory.find(params[:id])
  end
    
    def new
        @cathegory = Cathegory.new
    end
    
    def edit
        @cathegory = Cathegory.find(params[:id])
    end
      
    def create
        @cathegory = Cathegory.new(cathegory_params)
        if @cathegory.save
        redirect_to @cathegory
        else
        render 'new'
        end
    end
   
    def update
    @cathegory = Cathegory.find(params[:id])
        if @cathegory.update(cathegory_params)
        redirect_to @cathegory
        else
        render 'edit'
        end
    end

 private
  def cathegory_params
    params.require(:cathegory).permit(:cat, :description)
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
    
  def create
    @cathegory = Cathegory.find(params[:cathegory_id])
    @plant = @cathegory.plants.create(plant_params)
    redirect_to cathegory_path(@cathegory)
  end
   private
    def plant_params
      params.require(:plant).permit(:name, :family, :condition)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cathegories_helper.rb
module CathegoriesHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cathegories/edit.html.erb
<h1>Editing article</h1>
 <%= form_for :cathegory, url: cathegory_path(@cathegory), method: :patch do |f| %>
   
   <p>
    <%= f.label :cat %><br>
    <%= f.text_field :cat %>
  </p>
   <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
   <p>
    <%= f.submit %>
  </p>
   <% end %>
 <%= link_to 'Back', cathegories_path %>

app/views/cathegories/index.html.erb
<h1>Kategorie</h1>
 <%= link_to 'Nowa kategoria', new_cathegory_path %>
<table>
  <tr>
    <th>Cathegory</th>
    <th colspan="2"></th>
  </tr>
   <% @cathegories.each do |cathegory| %>
    <tr>
      <td><%= cathegory.cat %></td>
      <td><%= link_to 'Show', cathegory_path(cathegory) %></td>
      <td><%= link_to 'edit', edit_cathegory_path(cathegory) %></td>
    </tr>
  <% end %>
</table>

app/views/cathegories/new.html.erb
<h1>New Cathegory</h1>
<%= form_for :cathegory, url: cathegories_path do |f| %>
   


  <p>
    <%= f.label :cat %><br>
    <%= f.text_field :cat %>
  </p>
   <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
   <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', cathegories_path %>

app/views/cathegories/show.html.erb
<p>
  <strong>Cathegory:</strong>
  <%= @cathegory.cat %>
</p>
 <p>
  <strong>Description:</strong>
  <%= @cathegory.description %>
</p>

<h2>Rośliny</h2>
<% @cathegory.plants.each do |plant| %>
  <p>
    <strong>Roślina:</strong>
    <%= plant.name %>
   
  </p>
   
<% end %>


 <h2>Nowa roślina</h2>
<%= form_for([@cathegory, @cathegory.plants.build]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :family %><br>
    <%= f.text_area :family %>
  </p>
   <p>
    <%= f.label :condition %><br>
    <%= f.text_area :condition %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>


<%= link_to 'Back', cathegories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/plants/_plant.html.erb
<p>
  <strong>Nazwa:</strong>
  <%= plant.name %>
</p>
 <p>
  <strong>Rodzina:</strong>
  <%= plant.family %>
</p>
 <p>
  <strong>Uprawa:</strong>
  <%= plant.condition %>
</p>

app/views/plants/index.html.erb
<h1>Rośliny</h1>
 <%= link_to 'Nowa roślina', new_plant_path %>
<table>
  <tr>
    <th>Nazwa</th>
    <th colspan="2"></th>
  </tr>
   <% @plants.each do |plant| %>
    <tr>
      <td><%= plant.name %></td>
      
    </tr>
  <% end %>
</table>

app/views/plants/show.html.erb
<p>
  <strong>Nazwa:</strong>
  <%= @plant.name %>
</p>
 <p>
  <strong>Rodzina:</strong>
  <%= @plant.family %>
</p>

<p>
  tu będzie foto...
</p>

<p>
  <strong>Uprawa:</strong>
  <%= @plant.condition %>
</p>

<%= link_to 'Back', cathegories_path %>

app/views/welcome/index.html.erb
<%= link_to image_tag("meczennica_f3.jpg", alt: "logo"), '#' %>
<div class="center jumbotron">

    <h1>Hello, Rails!</h1>
</div>

<%= link_to 'back', controller: 'cathegories' %>